services:
  - type: web
    name: zomato-viz-dashboard
    env: python
    plan: free # Or your preferred plan
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn server:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11 # Or your preferred Python version
